### ISSUE TITLE
분기 처리 관련

### ISSUE THREAD

**Issue by mete0rfish** [mete0rfish/web-browser#3]
현재 server 소켓으로 요청이 올 경우, `handle_request`로 검색 관련 기능을 수행하는 것으로 파악했습니다. 단순히 웹 페이지를 보여주는 경우, 구글 검색과 어떻게 구분하여 처리하는 것이 좋을까요?

또한, 요청해서 받은 웹페이지를 react로 띄울 수 있는 방법도 있는지 궁금합니다.

**Comment by tnqkr3494** [comment]
일단 지금 구글에 GET요청 보낸걸 reponse받아와서 text형태로 `React`에 보내주고 있는데 `React`에서 그 전달 받은 text를 HTML형태로 볼 수 있게 해뒀습니다. 그런데 문제가 특수기호 몇개 깨지는 문제랑, 이미지가 안보이는 문제가 있어서 이걸 해결하는게 쉽지 않아보입니다. 
여차하면 아예 `React`로 띄우는걸 포기해야될 수도 있어서... 이 부분을 고민해서 해결해야 분기처리도 해결가능할 것 같습니다.

**Comment by mete0rfish** [comment]
@tnqkr3494 
react 적용 여부는 빠르게 결정해야 할 거 같습니다.
또한, `분기 처리`에 대해 답이 충분히 된지 않아 추가적인 설명 부탁드립니다!
